### ISSUE TITLE
Non-inernational

### ISSUE THREAD

**Issue by osswix** [DoctorAlpaca/dictionary#2]
Trying to use a script besides latin (not yet seen any working) will resut in squares,

http://puu.sh/d2wtW/9c619ce340.png

i hope this to be possible in future versions

^^. osswix

**Comment by cofl** [comment]
I checked, it's just the font. I'll add a fix to my pull request.

**Comment by osswix** [comment]
Thanks, where to add requested features btw?

Ps, WHERETHEFUCK did github get dis picture?

**Comment by cofl** [comment]
I'm not sure. DoctorAlpaca probably knows. Github got the picture from gravatar, so if you have a wordpress account, that's probably where.

**Comment by osswix** [comment]
i got a wanikani (japanese learning, but later i realized it would cost me money if i'd continue) one with gravatar ^^

**Comment by cofl** [comment]
I think I fixed it. Here's an unofficial build for now https://www.dropbox.com/s/zis33aci17trzco/dictionary-unofficial-build.jar?dl=0

**Comment by DoctorAlpaca** [comment]
You can label issues, and I just added a label for feature requests; so one can use that now.
